### ISSUE TITLE
Code review: Accessibility

### ISSUE THREAD

**Issue by ighellache** [fac26/Georgia-and-Karol#13]
At first glance the website was very clear and accessible - sections were easy to navigate and the images and colours were clear. We ran it against lighthouse which also showed a high accessibility score of 90 - awesome! (especially learning that Georgia has an interest in accessiblity).

**Comment by georgiaewhitney** [comment]
Thank you, both! Good to hear it hit 90, but still room to work and improve :)

**Comment by ko-karol** [comment]
Accessibility is a-ok.
