### ISSUE TITLE
Code review: The separate style CSS forms

### ISSUE THREAD

**Issue by ighellache** [fac26/Georgia-and-Karol#14]
Thank you for the clear classes and IDs - very easy to read and helpful if a newcomer wanted to develop with you. Just curious as to why you created separate style sheets for each HTML file (perhaps different working styles)? Regardless, love the javascript form file - we learned something new!

**Comment by ko-karol** [comment]
Hey, thanks for that! I'm glad you were able to read the css, personally I still find it pretty difficult to keep track of. The main reason I use separated css is simply for clarity.  There was quite a lot of css build up so I thought it would be best to keep them separate. Different working styles are also part of it, so good one. :)
