### ISSUE TITLE
Code Review: Link in navbar

### ISSUE THREAD

**Issue by LL835** [fac26/Georgia-and-Karol#15]
Hey again, we noticed that the 'who are we' and 'home' links in the navbar both go to 'index.html' (just in case you want to update these).
```
    <nav class='navbar'>
      <ul>
        <img class="logo" src="images/logo.svg" alt="logo" />
        <li><a class='home' href='index.html'>home</a></li>
        <li><a class='pagelink' href='index.html'>who are we</a></li>
        <li><a class='pagelink' href='contact-page/contact-page.html'>get in touch</a></li>
      </ul>
    </nav>
```

**Comment by ighellache** [comment]
Could direct "who are we" to a section of your index file instead? E.g. href=#ID_NAME (or class names)

**Comment by georgiaewhitney** [comment]
Thank you both! Good tip. 

I created the navbar, before defining the about us section a little lower down the page, so I will correct this now.

**Comment by georgiaewhitney** [comment]
Fixed this
