### ISSUE TITLE
Code review: Responsiveness

### ISSUE THREAD

**Issue by LL835** [fac26/Georgia-and-Karol#16]
The website is generally really responsive to different screen sizes. One thing we noticed was that the footer overlaps with the contact form on smaller screen sizes. Really impressive though and learn a lot from your media queries.

**Comment by ko-karol** [comment]
Awesome. Thanks for pointing out the footer is overlapping... we might have missed that.

**Comment by georgiaewhitney** [comment]
Thank you! We noticed some responsiveness differences between our two devices so we'll get this one fixed. Glad it's mostly all resizing well tho :)
