### ISSUE TITLE
Great to see so many commits

### ISSUE THREAD

**Issue by sofer** [fac26/Georgia-and-Karol#9]
Lovely to see both of you making so many commits 🚀 

Don't forget to make sure that the commits are telling a good story. "minor cleanup" and "refactor" don't tell us much about what you are working on.

Also, have a go at experimenting a bit with PRs.

**Comment by ko-karol** [comment]
Thank you Dan. Will try to make sure I put down more specific commits.

**Comment by georgiaewhitney** [comment]
Thanks Dan - ditto to what Karol said. I'll also try more Pull Requests
